# Generated by Django 2.1.7 on 2019-02-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('locale', models.CharField(max_length=250)),
                ('phoneNo', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('consumer_image', models.ImageField(blank=True, upload_to='media/consumer/')),
                ('ip_address', models.GenericIPAddressField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_name', models.CharField(max_length=200)),
                ('item_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('item_type', models.CharField(blank=True, max_length=200, null=True)),
                ('item_product_line', models.CharField(blank=True, max_length=200, null=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('item_quantity', models.FloatField()),
                ('item_manufacture', models.CharField(blank=True, max_length=200, null=True)),
                ('item_bought', models.DateTimeField(auto_now_add=True)),
                ('retail_consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.Consumer')),
            ],
        ),
    ]
